### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by rtemision** [tadatuta/bem-font-awesome#2]
Maybe replace the default bem tag `div` on the default (oil-oil :D) for font-awesome tag `i`? I think it's more universal, if need put it in some `span` for example.

**Comment by tadatuta** [comment]
Actually `<i>` has its own semantics and for example will be pronounced by screen readers which is wrong. Maybe we can replace `div` with `span` instead.

**Comment by denisbalyko** [comment]
From the official documentation:
> Font Awesome is designed to be used with inline elements (we like the `<i>` tag for brevity, but using a `<span>` is more semantically correct).

**Comment by tadatuta** [comment]
such brevity is quite useless after gzip compression
